spring:
    # 配置数据源信息
    datasource:
        # 配置数据源类型
        type: com.zaxxer.hikari.HikariDataSource
        # 配置连接数据库的各个信息
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
        username: root
        password: 12345678
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 设置mybatisplus的全局配置
    global-config:
        db-config:
            # 设置实体类所对应表的统一前缀
            table-prefix: t_
            # 配置主键id的生成策略为自动递增
            id-type: auto
    # 配置类型别名所对应的包
    type-aliases-package: usts.pycro.mybatisplus.pojo
    # 扫描通用枚举的包
    type-enums-package: usts.pycro.mybatisplus.enums